apiVersion: v1
kind: Service
metadata:
  name: wil-playground-svc
spec:
  selector:
    app: playground
  ports:
    - name: app-svc-port
      protocol: TCP
      port: 8888
      targetPort: playground-web
